mybatis:
  config-location: classpath:mybatis/mybatis-config.xml


spring:
  datasource:
    mysqldb:
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

    oracledb:
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:ORACLETEST
      username: oraclesun
      password: oraclesun
      driver-class-name: oracle.jdbc.driver.OracleDriver